### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ghost** [puuro-maria/artikkelitietokanta#1]
Ladattu 5.4. klo 18:20

Yleisellä tasolla toiminnot olivat fiksusti jaettuja ja pääsääntöisesti kaikki toimi kuten pitikin, hyvää työtä. Testatessa kävin tehdyiksi merkityt käyttötapaukset ja koodin läpi.

Suorittaminen:

-  Ensimmäisenä vastaantullut ongelma oli, että ohjelman suoritus hyytyi heti alkuunsa ImportErroriin. Syynä oli 'No module named author.models', joka oli seurausta ko. kansiosta puuttuneesta init.py tiedostosta. Sama toistui vielä reg, auth ja articleauthor kansioista, joihin init.py täytyi lisätä. Näiden lisäämisen jälkeen suoritus jatkui ongelmitta. 

Käyttöliittymä ja sen taustatoteutus:

-  Salasana ja salasana uudelleen kenttien validointi ei toimi, samoin vikaa on käyttäjätunnuksen ja nimen validoinnissa ja ne voi jättää rekisteröitymisessä tyhjäksi.

- Rekisteröidyttäessä ei tarkasteta onko käyttäjätunnusta jo olemassa, johtaen siihen, että sivulle voidaan luoda useita käyttäjiä samalla käyttäjätunnuksella ja salasanalla.

-  Uuden artikkelin lisäämisessä vuosiluvun validointi herjaa "This field is required." Kun käyttäjä syöttää kenttään kirjamia numeroiden sijaan, joka ei kuvaa varsinaista ongelmaa.

- Ei käyttötapauksissa, mutta yksi hyödyllinen käyttötapaus lisää olisi mahdollisuus merkata teos lukemattomaksi.

HTML:

- Navigointipalkissa on span-elementti, joka on määritelty sr-only, eli vain näytönlukijalle ja sen sisällä teksti (current). Elementti lienee ylimääräinen.

-  Ilmeisesti templates/artikkelit kansiosta löytyvä delete.html ei ole käytössä

Back end: 

- Muuttujien nimeämiseen voisi olla hyvä kiinnittää huomiota. Ulkopuoliselle lukijalle koodin seuraamista vaikeuttaa, jos muuttujia lyhennetään esim pelkäksi 	a:ksi tai au:ksi

**Comment by puuro-maria** [comment]
Vihdoin kaikki maininnat korjattu. Artikkelin merkkaamista lukemattomaksi ei tosin ainakaan vielä ole lisätty. Hyödyllinen ominaisuus kyllä ja helpohko toteuttaa - ehkä vielä ehdin. 

Muuttujien nimeämiseen kiinnitetty enemmän huomiota.
